# Generated by Django 5.1.4 on 2024-12-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admin',
            field=models.BooleanField(default=0),
        ),
    ]
