# Generated by Django 5.1.4 on 2024-12-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admin',
            field=models.BooleanField(default=1),
        ),
    ]
